name: GAME.BIN
sha1: 4d268b736fd5986994c9253ce4f3bf32eed2dbac
options:
  basename: game
  target_path: game/GAME.BIN
  elf_path: build/game.elf
  base_path: ..
  platform: psx
  compiler: PSYQ
  asm_path: asm/game
  src_path: src/game
  build_path: build/game
  ld_script_path: build/game.ld
  ld_dependencies: True
  find_file_boundaries: True
  o_as_suffix: True
  use_legacy_include_asm: False
  section_order: [".rodata", ".text", ".data", ".bss"]
  ld_bss_is_noload: False
  symbol_addrs_path:
    - symbol_addrs.txt
  reloc_addrs_path:
    - reloc_addrs.txt
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
segments:
  - name: game
    type: code
    start: 0x0
    vram: 0x800C1D4C
    exclusive_ram_id: vram_800c1d4c
    subsegments:
      - [0x0, asm, game]
  - [0x56604]
