name: TUTO.BIN
sha1: c599e185d3aabcaf44b8f44bad2dff8c90d7e9b9
options:
  basename: tuto
  target_path: game/TUTO.BIN
  elf_path: build/tuto.elf
  base_path: ..
  platform: psx
  compiler: PSYQ
  asm_path: asm/tuto
  src_path: src/tuto
  build_path: build/tuto
  ld_script_path: build/tuto.ld
  ld_dependencies: True
  find_file_boundaries: True
  o_as_suffix: True
  use_legacy_include_asm: False
  section_order: [".rodata", ".text", ".data", ".bss"]
  ld_bss_is_noload: False
  symbol_addrs_path:
    - symbol_addrs.txt
  reloc_addrs_path:
    - reloc_addrs.txt
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
segments:
  - name: tuto
    type: code
    start: 0x0
    vram: 0x80118350
    subsegments:
      - [0x0, asm, tuto]
  - [0x3C84]
